JPERF-1079 Make it possible to stop Jira nodes with a dedicated script.
atlassian/aws-infrastructure pull request #162
Opened 2023-04-27 13:55 UTC by ewefie

Remove deprecated constructors of Jira and CustomDatasetSource. Add to Jira information about its nodes.

2023-05-09 07:35 UTC, ewefie commented
Related PR https://github.com/atlassian/infrastructure/pull/155

2023-05-10 10:06 UTC, dagguh commented on gradle/dependency-locks/apiDependenciesMetadata.lockfile
> +com.atlassian.performance.tools:infrastructure:4.24.1
We bump this, because otherwise the tests wouldn't pass?

2023-05-10 10:17 UTC, dagguh requested changes

2023-05-10 10:17 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/StartedNode.kt
> +    class StoppableNode private constructor(
It's a `StartedNode.StoppableNode`, let's move it outside.

2023-05-10 10:17 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/StartedNode.kt
> +                )
```suggestion
                ssh.execute("source ~/.profile; ${jiraPath}/bin/stop-jira.sh", Duration.ofMinutes(3))
```

2023-05-10 10:17 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/StartedNode.kt
> +        fun stopNode() {
```suggestion
        fun stop() {
```

2023-05-10 10:17 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/StartedNode.kt
> +    }
```suggestion
    fun toStoppableNode(): StoppableNode = StoppableNode.Builder(jiraPath, ssh).build()
```

2023-05-10 10:17 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/Jira.kt
>  class Jira(
We added a builder, so can we hide the constructor?

2023-05-10 11:06 UTC, dagguh approved these changes

2023-05-10 12:17 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/Jira.kt
> -    val database: RemoteLocation?,
Are there any plans for support of databases that don't have file-based backups?

2023-05-10 12:22 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/Jira.kt
>      val jmxClients: List<JmxClient> = emptyList()
When we are breaking API did you consider unshipping JMX clients from the core Jira formulas?

2023-05-10 12:26 UTC, pczuj commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/jira/StartedNode.kt
> +    fun toStoppableNode(): StoppableNode = StoppableNode.Builder(jiraPath, ssh).build()
What's the reason for not making this "stoppability" a feature of `StartedNode`? I'm not sure if I understand the code modeling strategy here.

2023-05-24 11:23 UTC, pczuj approved these changes

2023-05-24 11:23 UTC, merged