Issue/jperf 1184 stop docker containers for real
atlassian/aws-infrastructure pull request #173
Opened 2023-07-10 07:26 UTC by ewefie

Add sudo to CustomDatasetSource.stopDockerContainers. 
We suspect that when we fail to close the MySQL container and proceed with archiving the database, the data inside might be corrupted.

2023-07-10 07:28 UTC, ewefie commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/CustomDatasetSource.kt
> +        Ssh(host, connectivityPatience = 4).newConnection().use { it.execute("sudo docker stop \$(sudo docker ps -aq)") }
I changed `safeExecute` to `execute` on purpose. We should be notified that something went wrong during this operation.

2023-07-12 10:32 UTC, dagguh requested changes

2023-07-12 10:32 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/CustomDatasetSourceIT.kt
> +        assertThat(use.output).isEmpty()
```suggestion
        val containerList = databaseSsh.newConnection().use { ssh ->
            ssh.execute("sudo docker ps -q")
        }
        assertThat(containerList.output).isEmpty()
```

2023-07-12 10:32 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/DatasetCatalogue.kt
> +    fun smallJiraNine(): Dataset = DatasetCatalogue().custom(
New API. Gotta changelog it

2023-07-14 11:49 UTC, dagguh approved these changes

2023-07-14 11:49 UTC, merged